[book]
authors = ["weibing.ma"]
language = "cn"
multilingual = false
src = "src"

[output.html] 
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
additional-css = ["theme/css/variables.css"] 
no-section-label = false
git-repository-url = "https://github.com/bertreyking/bertreyking.github.io" 
edit-url-template = "https://github.com/bertreyking/bertreyking.github.io" 