[book]
authors = ["weibing.ma"]
language = "cn"
multilingual = false
src = "src"

[output.html] 
theme = "theme"
default-theme = "rust"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
additional-css = ["theme/css/variables.css"] 
additional-js = ["theme/custom.js"]
no-section-label = false
git-repository-url = "https://github.com/bertreyking/bertreyking.github.io" 

[output.html.fold]
enable = true
level = 1
