site_name: MyWebSite
site_url: https://github.com/bertreyking/bertreyking.github.io/

nav:
    - Home: docs/index.md
    - Second: docs/second.md
    - Three: docs/three.md

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - markdown_checklist.extension

theme:
  name: material
