site_name: 贝特雷金
site_url: 'https://bertreyking.github.io/'
site_author: 'weibing.ma'
site_description: '个人事件记录'
copyright: '版权归个人所有'

nav:
    - Home: index.md
    - Linux:
        - 'CPU 负载分析': 'cpu_Load_Average分析.md'
        - 'CPU 上下文切换': 'cpu_上下文切换.md'
        - 'IPtables 使用': 'iptables.md'
        - 'TCPdump 抓包': 'tcpdump.md'
        - 'DNS 解析': 'dns.md'
        - 'JSON 数据处理': 'json_jq.md'
        - 'UPdate & UPgrade 区别': 'update_upgrade.md'
        - '快速查找清理文件': 'linux_find_du_mv_delete.md'
        - 'Ansible Playbook': 'ansible.md'

markdown_extensions:
    - toc:
        permalink: True
    - footnotes
    - tables
    - markdown_checklist.extension

theme:
    name: material
    palette: 
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

