# website_info
site_name: 贝特雷金
site_url: 'https://bertreyking.github.io/'
site_author: ‘bertreyking'
site_description: '个人笔记'
copyright: 'Copyright &copy; bertreyking'
repo_url: 'https://github.com/bertreyking/bertreyking.github.io'
repo_name: 'bertreyking/贝特雷金'
edit_uri: edit/main/docs/

# navlist_info
INHERIT: navigation.yml

# configation_info
markdown_extensions:
    - meta
    - def_list
    - attr_list
    - abbr
    - admonition
    - toc:
        permalink: True
        title: 导航
    - footnotes
    - tables
    - markdown_checklist.extension

theme:
    name: material

    include_search_page: false
    search_index_only: true
    include_homepage_in_sidebar: false

    icon:
        repo: fontawesome/brands/github

    palette: 
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

