<script src="https://giscus.app/client.js"
        data-repo="bertreyking/bertreyking.github.io"
        data-repo-id="R_kgDOJOGO-g"
        data-category="Announcements"
        data-category-id="DIC_kwDOJOGO-s4CV0Ol"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
